# settings
sudo: false 
dist: trusty
language: cpp
compiler: clang

# builds matrix
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8

before_script: 
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ughub/ughub install ugcore ProMesh SkinLayerGenerator
  - mkdir build && cd build && cmake ../ -DTARGET=ugshell -DLAPACK=OFF -DBLAS=OFF -DDIM="3" -DCPU=1 -DCOMPILE_INFO=OFF -DProMesh=ON -DSkinLayerGenerator=ON -DEMBEDDED_PLUGINS=OFF -DSLGTestsuite=ON
  - travis_wait 600 make

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /home/travis/build/NeuroBox3D/plugin_SkinLayerGenerator/bin/SLGTestsuite; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /Users/travis/build/NeuroBox3D/plugin_SkinLayerGenerator/bin/SLGTestsuite; fi
